### ISSUE TITLE
Question for computing power demand

### ISSUE THREAD

**Issue by Sunshine-Ye** [Megvii-BaseDetection/DynamicRouting#2]
Can you tell me the GPU cost when training from scratch and using ImageNet pre-training？(How long did it take under what and how many GPU)

**Comment by yanwei-li** [comment]
We use 4*2080Ti (2 image/GPU) for training. Layer16 Training from scratch (190K) and ImageNet pre-training (190K)  cost: within 2 days.  Training from scratch (560K): about 6 days.
