### ISSUE TITLE
FLops computation problem

### ISSUE THREAD

**Issue by guyuchao** [Megvii-BaseDetection/DynamicRouting#24]
You omit the flops computation of bilinear upsampling, have you benchmark the comparison methods in the same way?

**Comment by yanwei-li** [comment]
Thanks. We compute the Multi-Adds mainly from the convolution or related operations, which play a decisive role in FLOPS computation. Some of the compared methods do not release the source code officially, and some do not compute the neglected operations (especially compared with the computational overhead of the whole model) as well. So, we do not benchmark them exactly. Sorry for this omission.
