### ISSUE TITLE
Question about FLOPS_ALL

### ISSUE THREAD

**Issue by wzy199811** [Megvii-BaseDetection/DynamicRouting#25]
What does FLOPS_ALL mean? 
In your code, loss_BudgetConstraint=(flops_expt/FLOPS_ALL-loss_mu)^2. But according to your paper, it should be (flops_expt/flops_real-loss_mu)^2?

Thanks in advance.

**Comment by yanwei-li** [comment]
Hi, `FLOPS_ALL` in the code denotes the flops of all the nodes in the routing space, which is identical to that in the original paper.

**Comment by wzy199811** [comment]
Thank you for your reply.
I wonder why you use the flops_expt to train instead of flops_real. Because I think the flops_real is the real computational cost. I don't understand what the flops_expt actually means.

**Comment by yanwei-li** [comment]
Hi, `flops_expt` denotes the expection of flops, which is utilized for differentiable optimization by ` flops_expt / flops_all` in the [code](https://github.com/Megvii-BaseDetection/DynamicRouting/blob/6a88d018d30e1fdc3ea426a9c0db04dfebdcf2e3/dl_lib/modeling/meta_arch/dynamic4seg.py#L225). Actually, `flops_expt` can be viewed as the penalty of computation in each node, which is calculated by `flops_expt_node = flops_real_node * activated_prob`.

**Comment by wzy199811** [comment]
So when you train the model, sometimes it may just decrease the `activated_prob` but not change the dynamic route which is equivalent to not decrease the `flops_real`. Can it constrain the computational cost effectively?

**Comment by yanwei-li** [comment]
Actually, in the training stage, we aim to reduce `activated_prob` of useless nodes, which affect the `flops_real` in the inference stage, rather than decrease `flops_real` during optimization. Because we focus more on the inference computational cost.

**Comment by wzy199811** [comment]
Sorry, I still don't understand. If the `activated_prob` of every node is decreased to a very small value but greater than zero, your `flops_expt` will be low but the `flops_real` is still unchanged.

**Comment by yanwei-li** [comment]
Yes. Actually, most of `activated_prob` will converge to zero in the training, which is reflected in the Figure 5 of the main paper. This is why we use `max(0, tanh(.))` rather than `sigmoid(.)` to calculate the `activated_prob`.

**Comment by wzy199811** [comment]
Yes, most of `activated_prob` will converge to zero in the training, but still 30 to 50 percents are not zero. If use `flops_expt` to train, it can't decrease the `flops_real` but will decrease the `mIoU`.

**Comment by wzy199811** [comment]
So, I think it would get a better performance if use `flops_real` to train. Of course, that is just my personal opinion. I would appreciate it if you could point out my mistakes. Looking forward to your reply.

**Comment by yanwei-li** [comment]
Actually, you could not utilize `flops_real` to train directly. Imagine that you need to introduce `flops_real` to the network for end-to-end optimization, then the `flops_expt_node = flops_real_node * activated_prob` could be a simple solution. Because  `activated_prob` can be differentiable in the optimization process.

**Comment by wzy199811** [comment]
Thank you for your reply.
Oh, I get it. You use `flops_expt` to train because `flops_real` can't be utilized directly. I think there's a little problem with using `flops_expt` as I mentioned before but may no better way to deal with it, right?
I have another question. Why compare the sum of `activated_prob` with **0.0001** instead of **0**.

**Comment by yanwei-li** [comment]
We give a simple implementation with a threshold 1e-4, which is utilized to filter out the paths with very small probs. We believe better methods could be utilized to select the paths.

**Comment by wzy199811** [comment]
I see.
Thanks a lot.
