### ISSUE TITLE
Any code on inspecting how dynamic the model is?

### ISSUE THREAD

**Issue by sean-zhuh** [Megvii-BaseDetection/DynamicRouting#26]
Hi, do you have any code that enable to inspect how dynamic your model is? such as entropy or something similar.

**Comment by yanwei-li** [comment]
Hi, we have tried different types of [coefﬁcient of variation](https://arxiv.org/abs/1701.06538) to inspect and enlarge the dynamic gap, but found inferior performance. This is also illustrated in Sec. 4.4.3 of the main paper. But in my view, this could be further improved to better utilize the huge compacity of dynamic routing space.
