### ISSUE TITLE
datasets 路径配置

### ISSUE THREAD

**Issue by carlsummer** [Megvii-BaseDetection/DynamicRouting#28]
![image](https://user-images.githubusercontent.com/16281965/107107791-5b286f80-686e-11eb-81e4-9dbf7da7c57b.png)

**Comment by carlsummer** [comment]
默认的路径是：
/DynamicRouting/datasets/cityscapes/leftImg8bit/train 
/DynamicRouting/datasets/cityscapes/gtFine/train

**Comment by pzhren** [comment]
![image](https://user-images.githubusercontent.com/34993251/111155851-f8926400-85cf-11eb-9cfc-0f7803591bc3.png)
我出现了一些报错，不知道您是否可以帮忙看下，谢谢

**Comment by pzhren** [comment]
> ![image](https://user-images.githubusercontent.com/34993251/111155851-f8926400-85cf-11eb-9cfc-0f7803591bc3.png)
> 我出现了一些报错，不知道您是否可以帮忙看下，谢谢
我已经解决了，谢谢

**Comment by He9702** [comment]
我今天也遇到这个问题了，可以请教一下你是怎么解决的吗

**Comment by He9702** [comment]
> > ![image](https://user-images.githubusercontent.com/34993251/111155851-f8926400-85cf-11eb-9cfc-0f7803591bc3.png)
> > 我出现了一些报错，不知道您是否可以帮忙看下，谢谢
> > 我已经解决了，谢谢

我今天也遇到这个问题了，可以请教一下你是怎么解决的吗
