### ISSUE TITLE
about training on my own dataset

### ISSUE THREAD

**Issue by hhboy98** [Megvii-BaseDetection/DynamicRouting#29]
Hello, how to train this network on my own dataset

**Comment by yanwei-li** [comment]
Hi, there are two main steps to prepare:
1. Organize the data in ```DynamicRouting/datasets/```.
2. Add your own dataset mapper or processing in the files of ```DynamicRouting/dl_lib/data```.
Then you can use your own dataset with the predefined name in ```DATASETS``` of your config.
