### ISSUE TITLE
Questions aubout PSP Module / ASPP

### ISSUE THREAD

**Issue by TopTea1** [Megvii-BaseDetection/DynamicRouting#33]
Hi, I have a question regarding the PSPMosule you mentioned in the paper, is this module is placed at the output of the 1/32 line and then the results is added with the above line (1/16,1/8,1/4) ? Or is it placed at the 1/4 line and take as input the output of the simple decoder ? Moreover, have you tried the ASPP module combined with the decoder like in deeplabv3+ ?

I hope my questions were clear, and hanks in advance for your help !

**Comment by yanwei-li** [comment]
Hi, sorry for the late response. We add the PSP module at the 1/4 output. And we have tried ASPP (at the output of each scale 1/32, 1/16,1/8,1/4) but get a similar result with that of PSPNet

**Comment by TopTea1** [comment]
Thanks for the answer !
