### ISSUE TITLE
Question about the configs

### ISSUE THREAD

**Issue by baiwuchang** [Megvii-BaseDetection/DynamicRouting#34]
I noticed that the configs are only about the cityscapes dataset, so what is the config about the voc dataset?
Thanks in advance.

**Comment by yanwei-li** [comment]
Hi, the main difference between Cityscapes and VOC2012 is training strategy. This can be found in Section 4.2 of the [main paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Li_Learning_Dynamic_Routing_for_Semantic_Segmentation_CVPR_2020_paper.pdf).

**Comment by TopTea1** [comment]
Hi,  I see in your paper you use 512x512 image on val set did you use 0 padding to fit 512x512 images ?

**Comment by TopTea1** [comment]
Hi, I see you use 512x512 images for the validation, did you simply pad the images with 0 or did you resize the short edge to 512 and perform a center crop ? Thanks in advance

**Comment by yanwei-li** [comment]
Hi, as declared in the paper, we use 16 512x512 random crops per batch.
